version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
      - "9901:9901"
    network_mode: "host"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    network_mode: "host" 