version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
      - "9901:9901"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "8081:8081"

# Usage:
# 1. For macOS: docker compose up -d
# 2. For Linux with host networking: docker compose -f docker-compose.yml -f docker-compose.linux.yml up -d 